# Generated by Django 3.0.6 on 2020-05-29 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200529_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.Case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 9, 53, 18, 311537), verbose_name='date published'),
        ),
    ]
