# Generated by Django 3.0.6 on 2020-06-05 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200529_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='res_comp',
            field=models.BooleanField(default=False, verbose_name='complete result'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 14, 59, 20, 539929), verbose_name='date published'),
        ),
    ]
