# Generated by Django 3.0.6 on 2020-06-08 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200608_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 57, 31, 608379), verbose_name='date published'),
        ),
    ]
